-- TODO look into errors
-- TODO If we are putting it in the resources folder (could also be a normal folder), put some structure, like db -> schema or something

--CREATE TABLE users
--(
-- username varchar(100) NOT NULL,
-- userId varchar(11) NOT NULL ,
-- firstName varchar(100) NOT NULL,
-- lastName varchar(100) NOT NULL,
-- email varchar(100) NOT NULL,
-- password varchar(100) NOT NULL,
-- PRIMARY KEY (userId)
--);